FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY VLangsReact.Server/ .
WORKDIR /src
RUN dotnet restore VLangsReact.Server.csproj
RUN dotnet publish VLangsReact.Server.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
ENTRYPOINT ["dotnet", "VLangsReact.Server.dll"]
